version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql_password
      POSTGRES_DB: project
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: